### ISSUE TITLE
无法登录，感谢大佬

### ISSUE THREAD

**Issue by arraycto** [Zyfgoup/conferenceroomback#3]
您好，麻烦上传一下数据库的data，不然数据库是空的，无法登录，感谢大佬，向您学习

**Comment by Zyfgoup** [comment]
更新了 加了一些我自己测试时候的数据 管理员是admin 111111   部门或者员工都是编号作为账号的 密码好像是123456
密码好像都是MD5加密的 我忘了  你可以看看代码  密码不对的话 就找到加密方式 手动加密了直接修改数据库就行了

**Comment by arraycto** [comment]
非常好
